### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by sfc-gh-adlee** [xemuliam/docker-dbt#2]
Tried building the file after I cloned your repo : docker build -t leexha/dbt:0.21 --build-arg VERSION='0.21.1' --build-arg PLUGINS='bigquery snowflake,redshift' .

Gave error 

=> ERROR [build 1/1] RUN         apt-get update &&             apt-get install -y --no-install-recommends               software-properties-common               make               build-essential               libpq-dev               gcc               g++           1.6s
------
 > [build 1/1] RUN         apt-get update &&             apt-get install -y --no-install-recommends               software-properties-common               make               build-essential               libpq-dev               gcc               g++               libsasl2-dev               unixodbc-dev               curl &&             pip install --no-cache-dir --upgrade pip setuptools wheel &&             mkdir -p /usr/app &&             if [ -z "0.21.1" ]; then VERSION=$(curl -sL               https://api.github.com/repos/dbt-labs/dbt-core/releases/latest | grep tag_name |               tr -d ' ' | cut -d: -f 2,3 | tr -d " | tr -d , | tr -d v); fi &&             curl -L https://github.com/dbt-labs/dbt-core/archive/refs/tags/v0.21.1.tar.gz | tar xvz -C /usr/app &&             mv /usr/app/dbt-core-0.21.1/* /usr/app &&             rm -f *.tar.gz && rm -rf /usr/app/dbt-0.21.1 &&             cd /usr/app &&             > plugins.txt &&             for PLUGIN in $(echo 'core 'bigquery snowflake,redshift |               sed -e 's/\s/,/g' -e 's/\(,\)*/\1/g' -e 's/,/ /g'); do               echo dbt-${PLUGIN}'>='$(echo 0.21.1 | cut -d. -f 1,2) >> plugins.txt; done &&             pip wheel --wheel-dir /usr/app/wheels               --find-links /usr/app/wheels               --requirement plugins.txt:
#6 0.641 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
#6 0.664 Get:2 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
#6 0.724 Err:1 http://deb.debian.org/debian bullseye InRelease
#6 0.724   At least one invalid signature was encountered.
#6 0.769 Err:2 http://deb.debian.org/debian bullseye-updates InRelease

**Comment by xemuliam** [comment]
Hi @sfc-gh-adlee ,

thanks for your feedback.

First of all, the error shown in your log is related to Debian repositories unavailablity. Looks like smth. goes wrong at Debian repo store end. Try to run that build again a bit later.

And second observation: I see you try to use dockerfile related to new DBT versions (from 1.0.0). To build previous versions it is much better to use another dockerfile: `Dockerfile.old.before.1.0`

Anyway I'll be changing latest dockerfile to add backward compatibility for some latest DBT versions.

**Comment by xemuliam** [comment]
I've changed main dockerfile to add backward compatibility down to version 0.19.0
Enjoy! :)

**Comment by xemuliam** [comment]
No reponse from issue initiator. Closing...
