### ISSUE TITLE
Your version of dbt-core is out of date

### ISSUE THREAD

**Issue by MareoRaft** [xemuliam/docker-dbt#5]
When I try to run the image, I get error message:

```
Core:
  - installed: 1.1.0
  - latest:    1.1.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

I noticed that there is 1.1.0 version [here](https://hub.docker.com/r/xemuliam/dbt) but there is no 1.1.1 version.

How can we get latest version or somehow use older version without error?

**Comment by MareoRaft** [comment]
I'm also confused on how I can actually use dbt once I get the docker thing working.  For example, let's say I want to run the command `dbt run -m "otb_eligible_customer"`.  How would I do that with this docker image?  Do I need to do something like `docker exec my-dbt-image dbt -- run -m "otb_eligible_customer"`.  I just need to understand how to run the dbt command once it's installed.  This will also help me to verify if my installation is working or not.  Thank you!!

**Comment by avnav0** [comment]
having the same issue:

the entire thing is confusing, but i've somehow setup a way for this to work on this image and not the official...

```
step 1: pull image
	$	podman pull xemuliam/dbt
	
step 2: create a container through cli instead of dockerfile
	$	podman run -d --name dbt \
		-p 8085:8085 \
		-v /home/user/_volumes/_dbt/bigquery_bkup/try:/home/_dbt \
		xemuliam/dbt:latest
	
step 3: copy files from /usr/app to /home/_dbt
        $      podman exec -it dbt /bin/sh
	$	cp -R /usr/app/* /home/_dbt (inside container)
		exit
	$	podman stop dbt && podman rm dbt
	$	mkdir /home/user/_volumes/_dbt/_profiles
	$	touch /home/user/_volumes/_dbt/_profiles/profiles.yml
	
	
step 4: create a new volume
	$	podman run -d --name dbt \
		-p 8085:8085 \
		-v /home/user/_volumes/_dbt/bigquery_bkup/try:/usr/app/ \
		--mount type=bind,source=/home/user/_volumes/_dbt/_profiles/,target=/root/.dbt/ \
		xemuliam/dbt:latest
```

so, now i have the files for the app on local, and can play around with them.

```
step 5: create a project

$	podman exec -it dbt dbt init project_1 

```

**Comment by avnav0** [comment]
the problem is, if you try to install an adapter like for oracle the whole thing craps out because of the following notice i'd guess:

```
To avoid auto-downgrading of DBT-core version during outdated plugin installation, I've added strict condition that plugin's version must be equal to version of DBT-core.
```

**Comment by MareoRaft** [comment]
Thanks!  It sounds like you got it figured out and I'm using a different solution now so I'm going to close this issue.  Let me know if you want it reopened or something.
